services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.production # Loads all variables from here
    volumes:
      - ./public/images:/usr/src/app/public/images
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.production # Shares the same env file
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
