### GET / HOMEPAGE
GET http://localhost:3000

### GET /api/products
GET http://localhost:3000/api/products

### ENDPOINT FOR LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/x-www-form-urlencoded

username=baidocrazvan@yahoo.com&password=smiley79r

### ADD PRODUCT TO CART:
POST http://localhost:3000/api/cart/19
Content-Type: application/json

{
    "quantity": 7
}

### GET USER'S PRODUCTS FROM CART
GET http://localhost:3000/api/cart

### UPDATE QUANTITY FOR ITEM IN CART
PUT http://localhost:3000/api/cart
Content-Type: application/json

{
    "productId": 6,
    "quantity": 8
}

### DELETE PRODUCT FROM CART
DELETE http://localhost:3000/api/cart
Content-Type: application/json

{
    "productId": 6
}

### SEND ORDER WITH ITEMS IN CART
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "shippingAddress": "Ioan Slavici, Bl. R3, apt. 5"
}